python train_test.py --agg_method mean --subset_num 4 --experiment_name 4 --omics_mode abc --file_format npy --checkpoints_dir ./checkpoints/subset/agg_method/8_4_2_sub4 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2

python train_test.py --agg_method max --subset_num 4 --experiment_name 4 --omics_mode abc --file_format npy --checkpoints_dir ./checkpoints/subset/agg_method/8_4_2_sub4 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2

python train_test.py --agg_method sum --subset_num 4 --experiment_name 4 --omics_mode abc --file_format npy --checkpoints_dir ./checkpoints/subset/agg_method/8_4_2_sub4 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2

python train_test.py --agg_method min --subset_num 4 --experiment_name 4 --omics_mode abc --file_format npy --checkpoints_dir ./checkpoints/subset/agg_method/8_4_2_sub4 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2

python train_test.py --agg_method random --subset_num 4 --experiment_name 4 --omics_mode abc --file_format npy --checkpoints_dir ./checkpoints/subset/agg_method/8_4_2_sub4 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2

python train_test.py --use_subset_identity --agg_method mean --subset_num 4 --experiment_name 4 --omics_mode abc --file_format npy --checkpoints_dir ./checkpoints/subset/agg_method/8_4_2_sub4 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2
