python train_test.py --subset_num 7 --experiment_name 7 --omics_mode abc --file_format npy --checkpoints_dir ./checkpoints/subset/subset_num/8_4_2 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2 --use_subset_identity --agg_method mean

python train_test.py --omics_mode abc --experiment_name 8 --file_format npy --checkpoints_dir ./checkpoints/subset/subset_num/8_4_2 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --subset_num 8 --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2 --use_subset_identity --agg_method mean

python train_test.py --subset_num 9 --experiment_name 9 --omics_mode abc --file_format npy --checkpoints_dir ./checkpoints/subset/subset_num/8_4_2 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2 --use_subset_identity --agg_method mean

python train_test.py --subset_num 10 --experiment_name 10 --omics_mode abc --file_format npy --checkpoints_dir ./checkpoints/subset/subset_num/8_4_2 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2 --use_subset_identity --agg_method mean

python train_test.py --subset_num 11 --experiment_name 11 --omics_mode abc --file_format npy --checkpoints_dir ./checkpoints/subset/subset_num/8_4_2 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2 --use_subset_identity --agg_method mean

python train_test.py --subset_num 12 --experiment_name 12 --omics_mode abc --file_format npy --checkpoints_dir ./checkpoints/subset/subset_num/8_4_2 --data_root ./data/ABC_inter --use_sample_list --net_VAE fc --recon_loss MSE --k_embed 0.0001 --epoch_num_p1 15 --epoch_num_p2 0 --epoch_num_p3 115 --save_model --deterministic --use_subset_features --enc_reduction_factor 8 --dec_reduction_factor 4 --down_reduction_factor 2 --use_subset_identity --agg_method mean
